#!/bin/bash
set -e

echo "🚀 Building Focus Core for Apple Platforms..."

# 1. Ensure Rust targets are installed
echo "📦 Installing Rust iOS & macOS targets..."
rustup target add aarch64-apple-darwin x86_64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim

# 2. Compile for all targets
echo "🔨 Compiling Rust core..."
cargo build --lib --release --target aarch64-apple-darwin
cargo build --lib --release --target x86_64-apple-darwin
# cargo build --lib --release --target aarch64-apple-ios
# cargo build --lib --release --target aarch64-apple-ios-sim

# 3. Create Universal macOS binary
echo "🧬 Creating Universal macOS Binary..."
mkdir -p ../target/universal-macos/release
lipo -create -output ../target/universal-macos/release/libfocus_core.a \
    ../target/aarch64-apple-darwin/release/libfocus_core.a \
    ../target/x86_64-apple-darwin/release/libfocus_core.a

# 4. Generate Swift Bindings
echo "📝 Generating Swift bindings..."
mkdir -p generated_swift
cargo build --bin uniffi-bindgen
../target/debug/uniffi-bindgen generate --library ../target/aarch64-apple-darwin/release/libfocus_core.a --language swift --out-dir generated_swift

# Rename the header file for modulemap compliance if needed
# A module.modulemap is generated by uniffi automatically.

# 5. Package as XCFramework
echo "📦 Assembling XCFramework..."
rm -rf ../FocusCore.xcframework
# xcodebuild -create-xcframework \
#     -library ../target/universal-macos/release/libfocus_core.a -headers generated_swift \
#     -library ../target/aarch64-apple-ios/release/libfocus_core.a -headers generated_swift \
#     -library ../target/aarch64-apple-ios-sim/release/libfocus_core.a -headers generated_swift \
#     -output ../FocusCore.xcframework

xcodebuild -create-xcframework \
    -library ../target/universal-macos/release/libfocus_core.a -headers generated_swift \
    -output ../FocusCore.xcframework

echo "✅ Success! FocusCore.xcframework has been generated in the parent directory."
